// Type: BillingEntities.eJewishHoliday
// Assembly: BillingCalendar, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 44ED7BD3-A0FC-475F-9B75-C55DBACCBF0F
// Assembly location: D:\Tests\JewishHilidays\bin\BillingCalendar.dll

namespace BillingEntities
{
  public enum eJewishHoliday
  {
    RoshHodesh,
    ErevRoshHaShana,
    RoshHaShanaI,
    RoshHaShanaII,
    TzomGedaliah,
    ErevYomKippur,
    YomKippur,
    ErevSuccoth,
    Succoth,
    SuccothI,
    SuccothII,
    HolHamoed,
    HoschanaRaba,
    SheminiAtzeret,
    SimhathTorah,
    FastofTebeth,
    TuBiShevat,
    ShabbatHagadol,
    ErevPessach,
    PessachI,
    PessachII,
    PessachVII,
    PessachVIII,
    PessachVIIEve,
    YomHashoah,
    YomHazicaron,
    YomHaatzmaut,
    LagBaomer,
    ErevShavuoth,
    Shavuoth,
    ShavuothI,
    ShavuothII,
    TzomTammuz,
    FastofAv,
    ChanukkaI,
    ChanukkaII,
    ChanukkaIII,
    ChanukkaIV,
    ChanukkaV,
    ChanukkaVI,
    ChanukkaVII,
    ChanukkaVIII,
    FastOfEsther,
    Purim,
    ShushanPurim,
    PurimKatan,
    ShushanPurimKatan,
    Sigd,
    TuBeav,
    RabinMemorial,
  }
}
